### ISSUE TITLE
Web Of Chaos Missing From Quest Activity?

### ISSUE THREAD

**Issue by dragnilar** [Clemeit/ddo-audit#10]
Clemeit, 

I noticed Web of Chaos is not being tracked on the quest audit (or if it was, it suddenly disappeared):

![image](https://user-images.githubusercontent.com/33742520/227762304-d7ff74fd-cbdf-4a9c-98ec-0871a1895982.png)

I was pretty sure I saw Lords of Dust was at least being tracked at one point, but maybe I am wrong?

**Comment by Clemeit** [comment]
That Quests page has been such a pain. Lots of unexpected and weird behavior that I simply can't pin down. I'm not entirely sure why Lords of Dust decided to just stop showing up. I'm pretty sure it used to be tracked. Unfortunately this probably isn't something that I'll be able to look into any time soon. I'm hoping to completely redo all of the quest data collection stuff someday, but it'll have to wait.
