### ISSUE TITLE
hi,Clemeit,thanks for code

### ISSUE THREAD

**Issue by zhoushiya** [Clemeit/ddo-audit#4]
I user `npm run start` for the client and everything is fine, I can browse it at http://localhost:3000

but I user `npm run start` for  the server is not accessible ,i can't  browse it at http://localhost:8001

```
[root@localhost server]# npm run start

> ddo-audit-react@1.0.0 start
> nodemon app.js --ignore api_v1/

[nodemon] 2.0.16
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
API listening on undefined
Groups API connected to the database
Players API connected to the database
Message Service API connected to the database
Game Status API connected to the database
Activity API connected to the database
IOT API connected to the database

```

What should I do, please?

**Comment by Clemeit** [comment]
The server isn't going to run in your local environment because I don't ship database credentials with the rest of the codebase. I included the server code for transparency reasons, not necessarily to open it up to community development or contributions.
