### ISSUE TITLE
Why doesn't the activity endpoint include Isle of Dread?

### ISSUE THREAD

**Issue by dragnilar** [Clemeit/ddo-audit#7]
@Clemeit ,

I noticed that the activity endpoint doesn't seem to return any quest data for Isle of Dread and obviously it never displays in the grid on the quests view/page. Is this something that SSG would have to fix or is it a known issue you're working on?

**Comment by Clemeit** [comment]
@dragnilar Looks like I didn't finish hooking up the location data for the IoD quests. I have now completed this work and the quests should start being tracked as of today. Thanks for bringing it up.
