### ISSUE TITLE
Newer Content - 0 Avg XP/Min 

### ISSUE THREAD

**Issue by dragnilar** [Clemeit/ddo-audit#8]
@Clemeit 

I noticed that the newer dungeons are showing 0 for the XP/MIN calculation on the quests page:

![image](https://user-images.githubusercontent.com/33742520/203716717-3d4a8182-11b8-4a4e-816e-9bf581b7342c.png)

Do you need any help plugging the dungeons epic elite xp values for these in anywhere or is this something you can take care of on your own?

**Comment by Clemeit** [comment]
I used to go off of XP panel but I don't play DDO much anymore so now I rely on the Wiki. The last time I updated the quest XP was a while back. I've updated the values with the Wiki's most recent, but a handful are still missing.

**Comment by dragnilar** [comment]
@Clemeit  Ah makes sense. I was looking at those quests on the wiki and was debating getting those added. If you want, I will see about getting them updated.

 Do you want me to let you know them, if I manage to add those missing XP values?

**Comment by Clemeit** [comment]
Yeah, if you end up doing that let me know and I'll update them on my side. Thanks!

**Comment by dragnilar** [comment]
@Clemeit 

The missing epic elite values for Isle of Dread are up on the wiki now. I'll see if I can get around to the other ones later this week. 

https://ddowiki.com/page/The_Isle_of_Dread
