### ISSUE TITLE
Incorrect LFM numbers (Sarlona)

### ISSUE THREAD

**Issue by dooooken** [Clemeit/ddo-audit#9]
Not sure how often LFM data updates, but it's definitely not 0

![image](https://user-images.githubusercontent.com/92640214/223459221-15bab473-e718-42bf-ab82-844ec917092d.png)

EDIT:
Waiting a few more mins, the number once again updated to an incorrect number.
How often does the data update, and are there any exceptions that don't count into LFMs?

**Comment by Clemeit** [comment]
The number on the Servers page updates once every 5 minutes, so that's why it's not matching up. The number on the Grouping page, including the LFMs panels themselves, update every 15 seconds.

**Comment by Clemeit** [comment]
And the reason it said '0' is because there was an issue with the data collection this morning and I just recently fixed it.
